# Generated on Tue Feb  9 19:56:08 2021
__collection-name__: user-parameters

calibrate: 0
kd       : [0.2, 0.2, 0.2]
kp       : [50, 50, 50]
#q_init1   : [-0.6, -1.0, 2.7]
#q_init2   : [0.6, -1.0, 2.7]
#q_init3   : [-0.6, -1.0, 2.7]
#q_init4   : [0.6, -1.0, 2.7]
q_init1   : [-0.6, -1.0, 2.7]
q_init2   : [0.6, -1.0, 2.7]
q_init3   : [-0.6, -1.0, 2.7]
q_init4   : [0.6, -1.0, 2.7]
tau_ff   : 0
zero     : 0
