target_jpos: [
    -0.6, -1.0, 2.7,
    0.6, -1.0, 2.7,
    -0.6, -1.0, 2.7,
    0.6, -1.0, 2.7 ]

#target_jpos: [
#     0, -0.7854, 1.8326,
#     0, -0.7854, 1.8326,
#     0, -0.7854, 1.8326,
#     0, -0.7854, 1.8326]

#mid_jpos: [
#    0, 0., 0,
#    0, 0., 0,
#    0, 0., 0.,
#    0, 0., 0.]

mid_jpos: [
    -1.8, 0., 2.7,
    1.8, 0., 2.7,
    -1.7, 0.5, 0.5,
    1.7, 0.5, 0.5]

#mid_jpos2: [
#    -0.6, -1.0, 2.7,
#    0.6, -1.0, 2.7,
#    -0.6, -1.0, 2.7,
#    0.6, -1.0, 2.7 ]
